### ISSUE TITLE
type 'Null' is not a subtype of type 'bool' in type cast

### ISSUE THREAD

**Issue by kidusdev** [medz/prisma-dart#273] opened 2023-10-11 21:06 UTC
I Am using dart 3.1.3 and flutter 3.13.6 and when i run npx prisma generate it is terminating with an error
- Environment variables loaded from .env
Prisma schema loaded from prisma\schema.prisma
Error: 
type 'Null' is not a subtype of type 'bool' in type cast

**Comment by AndryHTC** [comment] 2023-10-15 14:50
@kidusdev duplicate of https://github.com/odroe/prisma-dart/issues/259

**Closed** 2023-11-27 13:21 UTC
Labels: bug
